# examples/hello-service.yaml
# Example Knative service for testing

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
      - image: gcr.io/knative-samples/helloworld-go
        ports:
        - containerPort: 8080
        env:
        - name: TARGET
          value: "Local Dev Cluster"
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"